zipf_offset: 15
outputs: debug/test
profile_path: debug/profile/test
dynamic_sp: true
dynamic_recompute: true
dummy_dataset: true
dummy_data_size: 4000


# ==== training config ====

# preprocess embedding
data_path: "./assets/example_data/demo_preprocess.csv"
preprocessed_data: true

# train
ckpt_path: "hpcai-tech/OpenSora-STDiT-v3"
grad_checkpoint: True
num_workers: 8
dtype: "bf16"

# log
seed: 42
epochs: 1
log_every: 1e10

# optimization
grad_clip: 1.0
lr: 1e-4
ema_decay: 0.99
adam_eps: 1e-15
warmup_steps: 10

# data
num_bucket_build_workers: 16
bucket_config:
  "720p": {408: [1.0, 2]}

# mask
mask_ratios: {
    "random": 0.01,
    "intepolate": 0.002,
    "quarter_random": 0.002,
    "quarter_head": 0.002,
    "quarter_tail": 0.002,
    "quarter_head_tail": 0.002,
    "image_random": 0.0,
    "image_head": 0.22,
    "image_tail": 0.005,
    "image_head_tail": 0.005,
}
